
spring.cloud.gcp.sql.database-name=mesadnd
spring.cloud.gcp.sql.instance-connection-name=iron-airfoil-271409:europe-west1:mesadnd

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url = jdbc:mysql://34.77.117.237/mesadnd?useSSL=false
## So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
## Enforces database initialization
spring.datasource.initialization-mode=always
spring.datasource.username=root
spring.datasource.password=yO5OqxBsNJajijcj

spring.jpa.properties.hibernate.default_schema=schema

server.port=8181